apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
type: Opaque
stringData:
  host: awx-instance-postgres-13
  port: "5432"
  database: awx
  username: awx
  password: awxpassword
  type: managed
