name: Deploy AWX on Kubernetes

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/awx-deployer

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # No secret check needed - workflow will fail if KUBECONFIG secret is not set
      
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Prepare kubeconfig
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
      run: |
        # Decode and save the kubeconfig
        echo "$KUBECONFIG_DATA" | base64 -d > /tmp/kubeconfig
        chmod 600 /tmp/kubeconfig
        
        # Validate the kubeconfig file
        echo "Validating kubeconfig..."
        if [ ! -s /tmp/kubeconfig ]; then
          echo "ERROR: kubeconfig file is empty!"
          exit 1
        fi
        
        # Check if it's a valid YAML file
        python3 -c "import yaml; yaml.safe_load(open('/tmp/kubeconfig'))" || { echo "ERROR: kubeconfig is not valid YAML!"; exit 1; }
        
        # Check if kubeconfig contains basic required fields
        grep -q "apiVersion:" /tmp/kubeconfig || { echo "ERROR: kubeconfig missing apiVersion field!"; exit 1; }
        grep -q "clusters:" /tmp/kubeconfig || { echo "ERROR: kubeconfig missing clusters section!"; exit 1; }
        grep -q "server:" /tmp/kubeconfig || { echo "ERROR: kubeconfig missing server URL!"; exit 1; }
        echo "Kubeconfig validation passed."

    - name: Debug image tags
      run: |
        echo "Available image tags:"
        echo "${{ steps.meta.outputs.tags }}"
        
    - name: Deploy AWX using containerized script
      run: |
        # Use the 'latest' tag if on main branch, otherwise use the first available tag
        TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1 | cut -d ' ' -f 1)
        echo "Using Docker image: $TAG"
        
        # Debug the kubeconfig content (excluding sensitive data)
        echo "Checking kubeconfig file exists and has content"
        ls -la /tmp/kubeconfig
        echo "File size: $(stat -c%s /tmp/kubeconfig) bytes"
        grep -i "server:" /tmp/kubeconfig || echo "No server entry found in kubeconfig"
        
        # Run the container with kubeconfig properly mounted
        docker run --rm \
          -v /tmp/kubeconfig:/kubeconfig:ro \
          -e KUBECONFIG=/kubeconfig \
          $TAG

    - name: Verify deployment
      run: |
        # Ensure kubeconfig is valid
        export KUBECONFIG=/tmp/kubeconfig
        echo "Testing kubectl connection before verification"
        kubectl cluster-info || { echo "Kubernetes cluster connection failed"; exit 1; }
        
        echo "Checking AWX deployment status..."
        kubectl get awx -n awx
        kubectl get pods -n awx
        kubectl get ingress -n awx
        
        echo "Waiting for AWX to be fully ready..."
        kubectl wait --for=condition=Running awx/awx-instance -n awx --timeout=600s || true
        
        echo "AWX Service Status:"
        kubectl get svc -n awx
        
        echo "AWX Ingress Status:"
        kubectl describe ingress -n awx || echo "No ingress found yet"

    - name: Get AWX access information
      run: |
        export KUBECONFIG=/tmp/kubeconfig
        echo "=========================="
        echo "AWX ACCESS INFORMATION"
        echo "=========================="
        echo "URL: https://awx.sin.padminisys.com"
        echo "Username: admin"
        
        # Verify kubectl connectivity
        kubectl cluster-info || { echo "WARNING: Unable to connect to Kubernetes cluster"; }
        
        # Try to get the admin password
        if kubectl get secret awx-admin-password -n awx >/dev/null 2>&1; then
          PASSWORD=$(kubectl get secret awx-admin-password -n awx -o jsonpath='{.data.password}' | base64 -d)
          echo "Password: $PASSWORD"
        else
          echo "Password: admin123!@# (default)"
        fi
        echo "=========================="

    - name: Cleanup
      if: always()
      run: |
        rm -f /tmp/kubeconfig
